# Site settings
title: Bibliothecarius Modernus
subtitle: The Modern Librarian
description: "Antiqua servare, nova quaerere"
baseurl: ""
url: ""

# Social media
youtube_username: BibliothecariusModernus
github_username: wryan14
archive_link: https://archive.org/details/@ryan_wolfslayer

# Additional resources
resource_links:
  latin_texts: https://github.com/wryan14/Latin-Patristic-Texts
  text_conversion: https://github.com/wryan14/TextractSSMLProcessor

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections:
  research:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Bibliothecarius Modernus"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
    values:
      image: "/assets/images/bibliothecarius-logo.png"

# Pagination
paginate: 6
paginate_path: "/page:num/"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md

# SEO settings
twitter:
  username: 
  card: summary_large_image
logo: /assets/images/bibliothecarius-logo.png
social:
  name: Bibliothecarius Modernus
  links:
    - https://youtube.com/@BibliothecariusModernus
    - https://github.com/wryan14
    - https://archive.org/details/@ryan_wolfslayer

# Google Analytics (if you want to add it later)
# google_analytics: UA-XXXXXXXX-X